export type CardCategory = 'birthday' | 'anniversary' | 'thankyou' | 'valentines' | 'wedding' | 'engagement' | 'babyshower' | 'graduation' | 'getwellsoon' | 'mothersday' | 'fathersday' | 'christmas' | 'hanukkah' | 'newyear' | 'lunarnewyear' | 'easter' | 'diwali' | 'ramadan' | 'vesak' | 'juneteenth' | 'invitation' | 'thinkingofyou' | 'motivation' | 'surprise';

export interface CardTemplate {
  id: string;
  category: CardCategory;
  name: string;
  title: string;
  frontImage: string | number;
  backMessage: string;
  color: string;
}

export const cardTemplates: CardTemplate[] = [
  // Birthday
  {
    id: 'birthday-1',
    category: 'birthday',
    name: 'Birthday 1',
    title: 'Happy Birthday!',
    frontImage: require('@/assets/images/cards/birthday/birthday-1.png'),
    backMessage: 'Wishing you a day filled with love, laughter, and unforgettable memories.',
    color: '#FFB6C1',
  },
  {
    id: 'birthday-2',
    category: 'birthday',
    name: 'Birthday 2',
    title: 'Happy Birthday!',
    frontImage: require('@/assets/images/cards/birthday/birthday-2.png'),
    backMessage: 'Wishing you a day filled with love, laughter, and unforgettable memories.',
    color: '#FFB6C1',
  },
  {
    id: 'birthday-3',
    category: 'birthday',
    name: 'Birthday 3',
    title: 'Happy Birthday!',
    frontImage: require('@/assets/images/cards/birthday/birthday-3.png'),
    backMessage: 'Wishing you a day filled with love, laughter, and unforgettable memories.',
    color: '#FFB6C1',
  },
  {
    id: 'birthday-4',
    category: 'birthday',
    name: 'Birthday 4',
    title: 'Happy Birthday!',
    frontImage: require('@/assets/images/cards/birthday/birthday-4.png'),
    backMessage: 'Wishing you a day filled with love, laughter, and unforgettable memories.',
    color: '#FFB6C1',
  },
  {
    id: 'birthday-5',
    category: 'birthday',
    name: 'Birthday 5',
    title: 'Happy Birthday!',
    frontImage: require('@/assets/images/cards/birthday/birthday-5.png'),
    backMessage: 'Wishing you a day filled with love, laughter, and unforgettable memories.',
    color: '#FFB6C1',
  },

  // Anniversary
  {
    id: 'anniversary-1',
    category: 'anniversary',
    name: 'Anniversary 1',
    title: 'Happy Anniversary!',
    frontImage: require('@/assets/images/cards/anniversary/anniversary-1.png'),
    backMessage: 'Wishing you love, joy, and many more beautiful moments together.',
    color: '#E8B4C0',
  },
  {
    id: 'anniversary-2',
    category: 'anniversary',
    name: 'Anniversary 2',
    title: 'Happy Anniversary!',
    frontImage: require('@/assets/images/cards/anniversary/anniversary-2.png'),
    backMessage: 'Wishing you love, joy, and many more beautiful moments together.',
    color: '#E8B4C0',
  },
  {
    id: 'anniversary-3',
    category: 'anniversary',
    name: 'Anniversary 3',
    title: 'Happy Anniversary!',
    frontImage: require('@/assets/images/cards/anniversary/anniversary-3.png'),
    backMessage: 'Wishing you love, joy, and many more beautiful moments together.',
    color: '#E8B4C0',
  },
  {
    id: 'anniversary-4',
    category: 'anniversary',
    name: 'Anniversary 4',
    title: 'Happy Anniversary!',
    frontImage: require('@/assets/images/cards/anniversary/anniversary-4.png'),
    backMessage: 'Wishing you love, joy, and many more beautiful moments together.',
    color: '#E8B4C0',
  },
  {
    id: 'anniversary-5',
    category: 'anniversary',
    name: 'Anniversary 5',
    title: 'Happy Anniversary!',
    frontImage: require('@/assets/images/cards/anniversary/anniversary-5.png'),
    backMessage: 'Wishing you love, joy, and many more beautiful moments together.',
    color: '#E8B4C0',
  },

  // Thank You
  {
    id: 'thankyou-1',
    category: 'thankyou',
    name: 'Thank You 1',
    title: 'Thank You!',
    frontImage: require('@/assets/images/cards/thankyou/thankyou-1.png'),
    backMessage: 'Thank you for your kindness, thoughtfulness, and support. It means so much.',
    color: '#E89BAE',
  },
  {
    id: 'thankyou-2',
    category: 'thankyou',
    name: 'Thank You 2',
    title: 'Thank You!',
    frontImage: require('@/assets/images/cards/thankyou/thankyou-2.png'),
    backMessage: 'Thank you for your kindness, thoughtfulness, and support. It means so much.',
    color: '#E89BAE',
  },
  {
    id: 'thankyou-3',
    category: 'thankyou',
    name: 'Thank You 3',
    title: 'Thank You!',
    frontImage: require('@/assets/images/cards/thankyou/thankyou-3.png'),
    backMessage: 'Thank you for your kindness, thoughtfulness, and support. It means so much.',
    color: '#E89BAE',
  },
  {
    id: 'thankyou-4',
    category: 'thankyou',
    name: 'Thank You 4',
    title: 'Thank You!',
    frontImage: require('@/assets/images/cards/thankyou/thankyou-4.png'),
    backMessage: 'Thank you for your kindness, thoughtfulness, and support. It means so much.',
    color: '#E89BAE',
  },
  {
    id: 'thankyou-5',
    category: 'thankyou',
    name: 'Thank You 5',
    title: 'Thank You!',
    frontImage: require('@/assets/images/cards/thankyou/thankyou-5.png'),
    backMessage: 'Thank you for your kindness, thoughtfulness, and support. It means so much.',
    color: '#E89BAE',
  },

  // Valentine's Day
  {
    id: 'valentines-1',
    category: 'valentines',
    name: 'Valentine\'s Day 1',
    title: 'Happy Valentine\'s Day!',
    frontImage: require('@/assets/images/cards/valentines/valentines-1.png'),
    backMessage: 'Sending love today and always. You make life sweeter and brighter.',
    color: '#F9A8D4',
  },
  {
    id: 'valentines-2',
    category: 'valentines',
    name: 'Valentine\'s Day 2',
    title: 'Happy Valentine\'s Day!',
    frontImage: require('@/assets/images/cards/valentines/valentines-2.png'),
    backMessage: 'Sending love today and always. You make life sweeter and brighter.',
    color: '#F9A8D4',
  },
  {
    id: 'valentines-3',
    category: 'valentines',
    name: 'Valentine\'s Day 3',
    title: 'Happy Valentine\'s Day!',
    frontImage: require('@/assets/images/cards/valentines/valentines-3.png'),
    backMessage: 'Sending love today and always. You make life sweeter and brighter.',
    color: '#F9A8D4',
  },
  {
    id: 'valentines-4',
    category: 'valentines',
    name: 'Valentine\'s Day 4',
    title: 'Happy Valentine\'s Day!',
    frontImage: require('@/assets/images/cards/valentines/valentines-4.png'),
    backMessage: 'Sending love today and always. You make life sweeter and brighter.',
    color: '#F9A8D4',
  },
  {
    id: 'valentines-5',
    category: 'valentines',
    name: 'Valentine\'s Day 5',
    title: 'Happy Valentine\'s Day!',
    frontImage: require('@/assets/images/cards/valentines/valentines-5.png'),
    backMessage: 'Sending love today and always. You make life sweeter and brighter.',
    color: '#F9A8D4',
  },

  // Wedding
  {
    id: 'wedding-1',
    category: 'wedding',
    name: 'Wedding 1',
    title: 'Congratulations!',
    frontImage: require('@/assets/images/cards/wedding/wedding-1.png'),
    backMessage: 'Wishing you a lifetime of love, laughter, and beautiful memories together.',
    color: '#F4D8E0',
  },
  {
    id: 'wedding-2',
    category: 'wedding',
    name: 'Wedding 2',
    title: 'Congratulations!',
    frontImage: require('@/assets/images/cards/wedding/wedding-2.png'),
    backMessage: 'Wishing you a lifetime of love, laughter, and beautiful memories together.',
    color: '#F4D8E0',
  },
  {
    id: 'wedding-3',
    category: 'wedding',
    name: 'Wedding 3',
    title: 'Congratulations!',
    frontImage: require('@/assets/images/cards/wedding/wedding-3.png'),
    backMessage: 'Wishing you a lifetime of love, laughter, and beautiful memories together.',
    color: '#F4D8E0',
  },
  {
    id: 'wedding-4',
    category: 'wedding',
    name: 'Wedding 4',
    title: 'Congratulations!',
    frontImage: require('@/assets/images/cards/wedding/wedding-4.png'),
    backMessage: 'Wishing you a lifetime of love, laughter, and beautiful memories together.',
    color: '#F4D8E0',
  },
  {
    id: 'wedding-5',
    category: 'wedding',
    name: 'Wedding 5',
    title: 'Congratulations!',
    frontImage: require('@/assets/images/cards/wedding/wedding-5.png'),
    backMessage: 'Wishing you a lifetime of love, laughter, and beautiful memories together.',
    color: '#F4D8E0',
  },

  // Engagement
  {
    id: 'engagement-1',
    category: 'engagement',
    name: 'Engagement 1',
    title: 'Congratulations!',
    frontImage: require('@/assets/images/cards/engagement/engagement-1.png'),
    backMessage: 'Congratulations on your engagement. Wishing you a lifetime of love and happiness together.',
    color: '#F5D6E0',
  },
  {
    id: 'engagement-2',
    category: 'engagement',
    name: 'Engagement 2',
    title: 'Congratulations!',
    frontImage: require('@/assets/images/cards/engagement/engagement-2.png'),
    backMessage: 'Congratulations on your engagement. Wishing you a lifetime of love and happiness together.',
    color: '#F5D6E0',
  },
  {
    id: 'engagement-3',
    category: 'engagement',
    name: 'Engagement 3',
    title: 'Congratulations!',
    frontImage: require('@/assets/images/cards/engagement/engagement-3.png'),
    backMessage: 'Congratulations on your engagement. Wishing you a lifetime of love and happiness together.',
    color: '#F5D6E0',
  },
  {
    id: 'engagement-4',
    category: 'engagement',
    name: 'Engagement 4',
    title: 'Congratulations!',
    frontImage: require('@/assets/images/cards/engagement/engagement-4.png'),
    backMessage: 'Congratulations on your engagement. Wishing you a lifetime of love and happiness together.',
    color: '#F5D6E0',
  },
  {
    id: 'engagement-5',
    category: 'engagement',
    name: 'Engagement 5',
    title: 'Congratulations!',
    frontImage: require('@/assets/images/cards/engagement/engagement-5.png'),
    backMessage: 'Congratulations on your engagement. Wishing you a lifetime of love and happiness together.',
    color: '#F5D6E0',
  },

  // Baby Shower
  {
    id: 'babyshower-1',
    category: 'babyshower',
    name: 'Baby Shower 1',
    title: 'Congratulations!',
    frontImage: require('@/assets/images/cards/babyshower/babyshower-1.png'),
    backMessage: 'Wishing your growing family endless love, joy, and precious memories.',
    color: '#F4DAE4',
  },
  {
    id: 'babyshower-2',
    category: 'babyshower',
    name: 'Baby Shower 2',
    title: 'Congratulations!',
    frontImage: require('@/assets/images/cards/babyshower/babyshower-2.png'),
    backMessage: 'Wishing your growing family endless love, joy, and precious memories.',
    color: '#F4DAE4',
  },
  {
    id: 'babyshower-3',
    category: 'babyshower',
    name: 'Baby Shower 3',
    title: 'Congratulations!',
    frontImage: require('@/assets/images/cards/babyshower/babyshower-3.png'),
    backMessage: 'Wishing your growing family endless love, joy, and precious memories.',
    color: '#F4DAE4',
  },
  {
    id: 'babyshower-4',
    category: 'babyshower',
    name: 'Baby Shower 4',
    title: 'Congratulations!',
    frontImage: require('@/assets/images/cards/babyshower/babyshower-4.png'),
    backMessage: 'Wishing your growing family endless love, joy, and precious memories.',
    color: '#F4DAE4',
  },
  {
    id: 'babyshower-5',
    category: 'babyshower',
    name: 'Baby Shower 5',
    title: 'Congratulations!',
    frontImage: require('@/assets/images/cards/babyshower/babyshower-5.png'),
    backMessage: 'Wishing your growing family endless love, joy, and precious memories.',
    color: '#F4DAE4',
  },

  // Graduation
  {
    id: 'graduation-1',
    category: 'graduation',
    name: 'Graduation 1',
    title: 'Congratulations, Graduate!',
    frontImage: require('@/assets/images/cards/graduation/graduation-1.png'),
    backMessage: 'Congratulations on this incredible achievement. The future is yours!',
    color: '#E8DCC8',
  },
  {
    id: 'graduation-2',
    category: 'graduation',
    name: 'Graduation 2',
    title: 'Congratulations, Graduate!',
    frontImage: require('@/assets/images/cards/graduation/graduation-2.png'),
    backMessage: 'Congratulations on this incredible achievement. The future is yours!',
    color: '#E8DCC8',
  },
  {
    id: 'graduation-3',
    category: 'graduation',
    name: 'Graduation 3',
    title: 'Congratulations, Graduate!',
    frontImage: require('@/assets/images/cards/graduation/graduation-3.png'),
    backMessage: 'Congratulations on this incredible achievement. The future is yours!',
    color: '#E8DCC8',
  },
  {
    id: 'graduation-4',
    category: 'graduation',
    name: 'Graduation 4',
    title: 'Congratulations, Graduate!',
    frontImage: require('@/assets/images/cards/graduation/graduation-4.png'),
    backMessage: 'Congratulations on this incredible achievement. The future is yours!',
    color: '#E8DCC8',
  },
  {
    id: 'graduation-5',
    category: 'graduation',
    name: 'Graduation 5',
    title: 'Congratulations, Graduate!',
    frontImage: require('@/assets/images/cards/graduation/graduation-5.png'),
    backMessage: 'Congratulations on this incredible achievement. The future is yours!',
    color: '#E8DCC8',
  },

  // Get Well Soon
  {
    id: 'getwellsoon-1',
    category: 'getwellsoon',
    name: 'Get Well Soon 1',
    title: 'Get Well Soon!',
    frontImage: require('@/assets/images/cards/getwellsoon/getwellsoon-1.png'),
    backMessage: 'Sending healing thoughts and warm wishes for a speedy recovery.',
    color: '#D4E8E8',
  },
  {
    id: 'getwellsoon-2',
    category: 'getwellsoon',
    name: 'Get Well Soon 2',
    title: 'Get Well Soon!',
    frontImage: require('@/assets/images/cards/getwellsoon/getwellsoon-2.png'),
    backMessage: 'Sending healing thoughts and warm wishes for a speedy recovery.',
    color: '#D4E8E8',
  },
  {
    id: 'getwellsoon-3',
    category: 'getwellsoon',
    name: 'Get Well Soon 3',
    title: 'Get Well Soon!',
    frontImage: require('@/assets/images/cards/getwellsoon/getwellsoon-3.png'),
    backMessage: 'Sending healing thoughts and warm wishes for a speedy recovery.',
    color: '#D4E8E8',
  },
  {
    id: 'getwellsoon-4',
    category: 'getwellsoon',
    name: 'Get Well Soon 4',
    title: 'Get Well Soon!',
    frontImage: require('@/assets/images/cards/getwellsoon/getwellsoon-4.png'),
    backMessage: 'Sending healing thoughts and warm wishes for a speedy recovery.',
    color: '#D4E8E8',
  },
  {
    id: 'getwellsoon-5',
    category: 'getwellsoon',
    name: 'Get Well Soon 5',
    title: 'Get Well Soon!',
    frontImage: require('@/assets/images/cards/getwellsoon/getwellsoon-5.png'),
    backMessage: 'Sending healing thoughts and warm wishes for a speedy recovery.',
    color: '#D4E8E8',
  },

  // Mother's Day
  {
    id: 'mothersday-1',
    category: 'mothersday',
    name: 'Mother\'s Day 1',
    title: 'Happy Mother\'s Day!',
    frontImage: require('@/assets/images/cards/mothersday/mothersday-1.png'),
    backMessage: 'Thank you for your endless love, care, and support. Happy Mother\'s Day!',
    color: '#F5C6D5',
  },
  {
    id: 'mothersday-2',
    category: 'mothersday',
    name: 'Mother\'s Day 2',
    title: 'Happy Mother\'s Day!',
    frontImage: require('@/assets/images/cards/mothersday/mothersday-2.png'),
    backMessage: 'Thank you for your endless love, care, and support. Happy Mother\'s Day!',
    color: '#F5C6D5',
  },
  {
    id: 'mothersday-3',
    category: 'mothersday',
    name: 'Mother\'s Day 3',
    title: 'Happy Mother\'s Day!',
    frontImage: require('@/assets/images/cards/mothersday/mothersday-3.png'),
    backMessage: 'Thank you for your endless love, care, and support. Happy Mother\'s Day!',
    color: '#F5C6D5',
  },
  {
    id: 'mothersday-4',
    category: 'mothersday',
    name: 'Mother\'s Day 4',
    title: 'Happy Mother\'s Day!',
    frontImage: require('@/assets/images/cards/mothersday/mothersday-4.png'),
    backMessage: 'Thank you for your endless love, care, and support. Happy Mother\'s Day!',
    color: '#F5C6D5',
  },
  {
    id: 'mothersday-5',
    category: 'mothersday',
    name: 'Mother\'s Day 5',
    title: 'Happy Mother\'s Day!',
    frontImage: require('@/assets/images/cards/mothersday/mothersday-5.png'),
    backMessage: 'Thank you for your endless love, care, and support. Happy Mother\'s Day!',
    color: '#F5C6D5',
  },

  // Father's Day
  {
    id: 'fathersday-1',
    category: 'fathersday',
    name: 'Father\'s Day 1',
    title: 'Happy Father\'s Day!',
    frontImage: require('@/assets/images/cards/fathersday/fathersday-1.png'),
    backMessage: 'Thank you for your love, guidance, and everything you do. Happy Father\'s Day!',
    color: '#1F2937',
  },
  {
    id: 'fathersday-2',
    category: 'fathersday',
    name: 'Father\'s Day 2',
    title: 'Happy Father\'s Day!',
    frontImage: require('@/assets/images/cards/fathersday/fathersday-2.png'),
    backMessage: 'Thank you for your love, guidance, and everything you do. Happy Father\'s Day!',
    color: '#1F2937',
  },
  {
    id: 'fathersday-3',
    category: 'fathersday',
    name: 'Father\'s Day 3',
    title: 'Happy Father\'s Day!',
    frontImage: require('@/assets/images/cards/fathersday/fathersday-3.png'),
    backMessage: 'Thank you for your love, guidance, and everything you do. Happy Father\'s Day!',
    color: '#1F2937',
  },
  {
    id: 'fathersday-4',
    category: 'fathersday',
    name: 'Father\'s Day 4',
    title: 'Happy Father\'s Day!',
    frontImage: require('@/assets/images/cards/fathersday/fathersday-4.png'),
    backMessage: 'Thank you for your love, guidance, and everything you do. Happy Father\'s Day!',
    color: '#1F2937',
  },
  {
    id: 'fathersday-5',
    category: 'fathersday',
    name: 'Father\'s Day 5',
    title: 'Happy Father\'s Day!',
    frontImage: require('@/assets/images/cards/fathersday/fathersday-5.png'),
    backMessage: 'Thank you for your love, guidance, and everything you do. Happy Father\'s Day!',
    color: '#1F2937',
  },

  // Christmas
  {
    id: 'christmas-1',
    category: 'christmas',
    name: 'Christmas 1',
    title: 'Merry Christmas!',
    frontImage: require('@/assets/images/cards/christmas/christmas-1.png'),
    backMessage: 'Wishing you a warm and wonderful Christmas filled with joy, love, and peace.',
    color: '#5D8C6F',
  },
  {
    id: 'christmas-2',
    category: 'christmas',
    name: 'Christmas 2',
    title: 'Merry Christmas!',
    frontImage: require('@/assets/images/cards/christmas/christmas-2.png'),
    backMessage: 'Wishing you a warm and wonderful Christmas filled with joy, love, and peace.',
    color: '#5D8C6F',
  },
  {
    id: 'christmas-3',
    category: 'christmas',
    name: 'Christmas 3',
    title: 'Merry Christmas!',
    frontImage: require('@/assets/images/cards/christmas/christmas-3.png'),
    backMessage: 'Wishing you a warm and wonderful Christmas filled with joy, love, and peace.',
    color: '#5D8C6F',
  },
  {
    id: 'christmas-4',
    category: 'christmas',
    name: 'Christmas 4',
    title: 'Merry Christmas!',
    frontImage: require('@/assets/images/cards/christmas/christmas-4.png'),
    backMessage: 'Wishing you a warm and wonderful Christmas filled with joy, love, and peace.',
    color: '#5D8C6F',
  },
  {
    id: 'christmas-5',
    category: 'christmas',
    name: 'Christmas 5',
    title: 'Merry Christmas!',
    frontImage: require('@/assets/images/cards/christmas/christmas-5.png'),
    backMessage: 'Wishing you a warm and wonderful Christmas filled with joy, love, and peace.',
    color: '#5D8C6F',
  },

  // Hanukkah
  {
    id: 'hanukkah-1',
    category: 'hanukkah',
    name: 'Hanukkah 1',
    title: 'Happy Hanukkah!',
    frontImage: require('@/assets/images/cards/hanukkah/hanukkah-1.png'),
    backMessage: 'Wishing you peace, light, love, and happiness throughout Hanukkah.',
    color: '#A8C8E1',
  },
  {
    id: 'hanukkah-2',
    category: 'hanukkah',
    name: 'Hanukkah 2',
    title: 'Happy Hanukkah!',
    frontImage: require('@/assets/images/cards/hanukkah/hanukkah-2.png'),
    backMessage: 'Wishing you peace, light, love, and happiness throughout Hanukkah.',
    color: '#A8C8E1',
  },
  {
    id: 'hanukkah-3',
    category: 'hanukkah',
    name: 'Hanukkah 3',
    title: 'Happy Hanukkah!',
    frontImage: require('@/assets/images/cards/hanukkah/hanukkah-3.png'),
    backMessage: 'Wishing you peace, light, love, and happiness throughout Hanukkah.',
    color: '#A8C8E1',
  },
  {
    id: 'hanukkah-4',
    category: 'hanukkah',
    name: 'Hanukkah 4',
    title: 'Happy Hanukkah!',
    frontImage: require('@/assets/images/cards/hanukkah/hanukkah-4.png'),
    backMessage: 'Wishing you peace, light, love, and happiness throughout Hanukkah.',
    color: '#A8C8E1',
  },
  {
    id: 'hanukkah-5',
    category: 'hanukkah',
    name: 'Hanukkah 5',
    title: 'Happy Hanukkah!',
    frontImage: require('@/assets/images/cards/hanukkah/hanukkah-5.png'),
    backMessage: 'Wishing you peace, light, love, and happiness throughout Hanukkah.',
    color: '#A8C8E1',
  },

  // New Year
  {
    id: 'newyear-1',
    category: 'newyear',
    name: 'New Year 1',
    title: 'Happy New Year!',
    frontImage: require('@/assets/images/cards/newyear/newyear-1.png'),
    backMessage: 'Wishing you a joyful new year filled with fresh beginnings and beautiful moments.',
    color: '#FCD34D',
  },
  {
    id: 'newyear-2',
    category: 'newyear',
    name: 'New Year 2',
    title: 'Happy New Year!',
    frontImage: require('@/assets/images/cards/newyear/newyear-2.png'),
    backMessage: 'Wishing you a joyful new year filled with fresh beginnings and beautiful moments.',
    color: '#FCD34D',
  },
  {
    id: 'newyear-3',
    category: 'newyear',
    name: 'New Year 3',
    title: 'Happy New Year!',
    frontImage: require('@/assets/images/cards/newyear/newyear-3.png'),
    backMessage: 'Wishing you a joyful new year filled with fresh beginnings and beautiful moments.',
    color: '#FCD34D',
  },
  {
    id: 'newyear-4',
    category: 'newyear',
    name: 'New Year 4',
    title: 'Happy New Year!',
    frontImage: require('@/assets/images/cards/newyear/newyear-4.png'),
    backMessage: 'Wishing you a joyful new year filled with fresh beginnings and beautiful moments.',
    color: '#FCD34D',
  },
  {
    id: 'newyear-5',
    category: 'newyear',
    name: 'New Year 5',
    title: 'Happy New Year!',
    frontImage: require('@/assets/images/cards/newyear/newyear-5.png'),
    backMessage: 'Wishing you a joyful new year filled with fresh beginnings and beautiful moments.',
    color: '#FCD34D',
  },

  // Lunar New Year
  {
    id: 'lunarnewyear-1',
    category: 'lunarnewyear',
    name: 'Lunar New Year 1',
    title: 'Happy Lunar New Year!',
    frontImage: require('@/assets/images/cards/lunarnewyear/lunarnewyear-1.png'),
    backMessage: 'Wishing you prosperity, good fortune, happiness, and a joyful Lunar New Year.',
    color: '#DC2626',
  },
  {
    id: 'lunarnewyear-2',
    category: 'lunarnewyear',
    name: 'Lunar New Year 2',
    title: 'Happy Lunar New Year!',
    frontImage: require('@/assets/images/cards/lunarnewyear/lunarnewyear-2.png'),
    backMessage: 'Wishing you prosperity, good fortune, happiness, and a joyful Lunar New Year.',
    color: '#DC2626',
  },
  {
    id: 'lunarnewyear-3',
    category: 'lunarnewyear',
    name: 'Lunar New Year 3',
    title: 'Happy Lunar New Year!',
    frontImage: require('@/assets/images/cards/lunarnewyear/lunarnewyear-3.png'),
    backMessage: 'Wishing you prosperity, good fortune, happiness, and a joyful Lunar New Year.',
    color: '#DC2626',
  },
  {
    id: 'lunarnewyear-4',
    category: 'lunarnewyear',
    name: 'Lunar New Year 4',
    title: 'Happy Lunar New Year!',
    frontImage: require('@/assets/images/cards/lunarnewyear/lunarnewyear-4.png'),
    backMessage: 'Wishing you prosperity, good fortune, happiness, and a joyful Lunar New Year.',
    color: '#DC2626',
  },
  {
    id: 'lunarnewyear-5',
    category: 'lunarnewyear',
    name: 'Lunar New Year 5',
    title: 'Happy Lunar New Year!',
    frontImage: require('@/assets/images/cards/lunarnewyear/lunarnewyear-5.png'),
    backMessage: 'Wishing you prosperity, good fortune, happiness, and a joyful Lunar New Year.',
    color: '#DC2626',
  },

  // Easter
  {
    id: 'easter-1',
    category: 'easter',
    name: 'Easter 1',
    title: 'Happy Easter!',
    frontImage: require('@/assets/images/cards/easter/easter-1.png'),
    backMessage: 'Wishing you a bright and joyful Easter filled with hope, love, and renewal.',
    color: '#FFE680',
  },
  {
    id: 'easter-2',
    category: 'easter',
    name: 'Easter 2',
    title: 'Happy Easter!',
    frontImage: require('@/assets/images/cards/easter/easter-2.png'),
    backMessage: 'Wishing you a bright and joyful Easter filled with hope, love, and renewal.',
    color: '#FFE680',
  },
  {
    id: 'easter-3',
    category: 'easter',
    name: 'Easter 3',
    title: 'Happy Easter!',
    frontImage: require('@/assets/images/cards/easter/easter-3.png'),
    backMessage: 'Wishing you a bright and joyful Easter filled with hope, love, and renewal.',
    color: '#FFE680',
  },
  {
    id: 'easter-4',
    category: 'easter',
    name: 'Easter 4',
    title: 'Happy Easter!',
    frontImage: require('@/assets/images/cards/easter/easter-4.png'),
    backMessage: 'Wishing you a bright and joyful Easter filled with hope, love, and renewal.',
    color: '#FFE680',
  },
  {
    id: 'easter-5',
    category: 'easter',
    name: 'Easter 5',
    title: 'Happy Easter!',
    frontImage: require('@/assets/images/cards/easter/easter-5.png'),
    backMessage: 'Wishing you a bright and joyful Easter filled with hope, love, and renewal.',
    color: '#FFE680',
  },

  // Diwali
  {
    id: 'diwali-1',
    category: 'diwali',
    name: 'Diwali 1',
    title: 'Happy Diwali!',
    frontImage: require('@/assets/images/cards/diwali/diwali-1.png'),
    backMessage: 'Wishing you light, joy, prosperity, and beautiful celebrations this Diwali.',
    color: '#F7B500',
  },
  {
    id: 'diwali-2',
    category: 'diwali',
    name: 'Diwali 2',
    title: 'Happy Diwali!',
    frontImage: require('@/assets/images/cards/diwali/diwali-2.png'),
    backMessage: 'Wishing you light, joy, prosperity, and beautiful celebrations this Diwali.',
    color: '#F7B500',
  },
  {
    id: 'diwali-3',
    category: 'diwali',
    name: 'Diwali 3',
    title: 'Happy Diwali!',
    frontImage: require('@/assets/images/cards/diwali/diwali-3.png'),
    backMessage: 'Wishing you light, joy, prosperity, and beautiful celebrations this Diwali.',
    color: '#F7B500',
  },
  {
    id: 'diwali-4',
    category: 'diwali',
    name: 'Diwali 4',
    title: 'Happy Diwali!',
    frontImage: require('@/assets/images/cards/diwali/diwali-4.png'),
    backMessage: 'Wishing you light, joy, prosperity, and beautiful celebrations this Diwali.',
    color: '#F7B500',
  },
  {
    id: 'diwali-5',
    category: 'diwali',
    name: 'Diwali 5',
    title: 'Happy Diwali!',
    frontImage: require('@/assets/images/cards/diwali/diwali-5.png'),
    backMessage: 'Wishing you light, joy, prosperity, and beautiful celebrations this Diwali.',
    color: '#F7B500',
  },

  // Ramadan
  {
    id: 'ramadan-1',
    category: 'ramadan',
    name: 'Ramadan 1',
    title: 'Ramadan Kareem!',
    frontImage: require('@/assets/images/cards/ramadan/ramadan-1.png'),
    backMessage: 'Wishing you a blessed Ramadan filled with peace, reflection, and kindness.',
    color: '#14532D',
  },
  {
    id: 'ramadan-2',
    category: 'ramadan',
    name: 'Ramadan 2',
    title: 'Ramadan Kareem!',
    frontImage: require('@/assets/images/cards/ramadan/ramadan-2.png'),
    backMessage: 'Wishing you a blessed Ramadan filled with peace, reflection, and kindness.',
    color: '#14532D',
  },
  {
    id: 'ramadan-3',
    category: 'ramadan',
    name: 'Ramadan 3',
    title: 'Ramadan Kareem!',
    frontImage: require('@/assets/images/cards/ramadan/ramadan-3.png'),
    backMessage: 'Wishing you a blessed Ramadan filled with peace, reflection, and kindness.',
    color: '#14532D',
  },
  {
    id: 'ramadan-4',
    category: 'ramadan',
    name: 'Ramadan 4',
    title: 'Ramadan Kareem!',
    frontImage: require('@/assets/images/cards/ramadan/ramadan-4.png'),
    backMessage: 'Wishing you a blessed Ramadan filled with peace, reflection, and kindness.',
    color: '#14532D',
  },
  {
    id: 'ramadan-5',
    category: 'ramadan',
    name: 'Ramadan 5',
    title: 'Ramadan Kareem!',
    frontImage: require('@/assets/images/cards/ramadan/ramadan-5.png'),
    backMessage: 'Wishing you a blessed Ramadan filled with peace, reflection, and kindness.',
    color: '#14532D',
  },

  // Vesak
  {
    id: 'vesak-1',
    category: 'vesak',
    name: 'Vesak 1',
    title: 'Happy Vesak Day!',
    frontImage: require('@/assets/images/cards/vesak/vesak-1.png'),
    backMessage: 'Wishing you peace, compassion, mindfulness, and blessings on Vesak Day.',
    color: '#92400E',
  },
  {
    id: 'vesak-2',
    category: 'vesak',
    name: 'Vesak 2',
    title: 'Happy Vesak Day!',
    frontImage: require('@/assets/images/cards/vesak/vesak-2.png'),
    backMessage: 'Wishing you peace, compassion, mindfulness, and blessings on Vesak Day.',
    color: '#92400E',
  },
  {
    id: 'vesak-3',
    category: 'vesak',
    name: 'Vesak 3',
    title: 'Happy Vesak Day!',
    frontImage: require('@/assets/images/cards/vesak/vesak-3.png'),
    backMessage: 'Wishing you peace, compassion, mindfulness, and blessings on Vesak Day.',
    color: '#92400E',
  },
  {
    id: 'vesak-4',
    category: 'vesak',
    name: 'Vesak 4',
    title: 'Happy Vesak Day!',
    frontImage: require('@/assets/images/cards/vesak/vesak-4.png'),
    backMessage: 'Wishing you peace, compassion, mindfulness, and blessings on Vesak Day.',
    color: '#92400E',
  },
  {
    id: 'vesak-5',
    category: 'vesak',
    name: 'Vesak 5',
    title: 'Happy Vesak Day!',
    frontImage: require('@/assets/images/cards/vesak/vesak-5.png'),
    backMessage: 'Wishing you peace, compassion, mindfulness, and blessings on Vesak Day.',
    color: '#92400E',
  },

  // Juneteenth
  {
    id: 'juneteenth-1',
    category: 'juneteenth',
    name: 'Juneteenth 1',
    title: 'Happy Juneteenth!',
    frontImage: require('@/assets/images/cards/juneteenth/juneteenth-1.png'),
    backMessage: 'Celebrating freedom, resilience, joy, and community this Juneteenth.',
    color: '#F97316',
  },
  {
    id: 'juneteenth-2',
    category: 'juneteenth',
    name: 'Juneteenth 2',
    title: 'Happy Juneteenth!',
    frontImage: require('@/assets/images/cards/juneteenth/juneteenth-2.png'),
    backMessage: 'Celebrating freedom, resilience, joy, and community this Juneteenth.',
    color: '#F97316',
  },
  {
    id: 'juneteenth-3',
    category: 'juneteenth',
    name: 'Juneteenth 3',
    title: 'Happy Juneteenth!',
    frontImage: require('@/assets/images/cards/juneteenth/juneteenth-3.png'),
    backMessage: 'Celebrating freedom, resilience, joy, and community this Juneteenth.',
    color: '#F97316',
  },
  {
    id: 'juneteenth-4',
    category: 'juneteenth',
    name: 'Juneteenth 4',
    title: 'Happy Juneteenth!',
    frontImage: require('@/assets/images/cards/juneteenth/juneteenth-4.png'),
    backMessage: 'Celebrating freedom, resilience, joy, and community this Juneteenth.',
    color: '#F97316',
  },
  {
    id: 'juneteenth-5',
    category: 'juneteenth',
    name: 'Juneteenth 5',
    title: 'Happy Juneteenth!',
    frontImage: require('@/assets/images/cards/juneteenth/juneteenth-5.png'),
    backMessage: 'Celebrating freedom, resilience, joy, and community this Juneteenth.',
    color: '#F97316',
  },

  // Invitation
  {
    id: 'invitation-1',
    category: 'invitation',
    name: 'Invitation 1',
    title: 'You\'re Invited!',
    frontImage: require('@/assets/images/cards/invitation/invitation-1.png'),
    backMessage: 'You are invited to celebrate, gather, and make wonderful memories together.',
    color: '#7A8B73',
  },
  {
    id: 'invitation-2',
    category: 'invitation',
    name: 'Invitation 2',
    title: 'You\'re Invited!',
    frontImage: require('@/assets/images/cards/invitation/invitation-2.png'),
    backMessage: 'You are invited to celebrate, gather, and make wonderful memories together.',
    color: '#7A8B73',
  },
  {
    id: 'invitation-3',
    category: 'invitation',
    name: 'Invitation 3',
    title: 'You\'re Invited!',
    frontImage: require('@/assets/images/cards/invitation/invitation-3.png'),
    backMessage: 'You are invited to celebrate, gather, and make wonderful memories together.',
    color: '#7A8B73',
  },
  {
    id: 'invitation-4',
    category: 'invitation',
    name: 'Invitation 4',
    title: 'You\'re Invited!',
    frontImage: require('@/assets/images/cards/invitation/invitation-4.png'),
    backMessage: 'You are invited to celebrate, gather, and make wonderful memories together.',
    color: '#7A8B73',
  },
  {
    id: 'invitation-5',
    category: 'invitation',
    name: 'Invitation 5',
    title: 'You\'re Invited!',
    frontImage: require('@/assets/images/cards/invitation/invitation-5.png'),
    backMessage: 'You are invited to celebrate, gather, and make wonderful memories together.',
    color: '#7A8B73',
  },

  // Thinking of You
  {
    id: 'thinkingofyou-1',
    category: 'thinkingofyou',
    name: 'Thinking of You 1',
    title: 'Thinking of You',
    frontImage: require('@/assets/images/cards/thinkingofyou/thinkingofyou-1.png'),
    backMessage: 'Just wanted you to know you are on my mind and in my heart today.',
    color: '#A8B59A',
  },
  {
    id: 'thinkingofyou-2',
    category: 'thinkingofyou',
    name: 'Thinking of You 2',
    title: 'Thinking of You',
    frontImage: require('@/assets/images/cards/thinkingofyou/thinkingofyou-2.png'),
    backMessage: 'Just wanted you to know you are on my mind and in my heart today.',
    color: '#A8B59A',
  },
  {
    id: 'thinkingofyou-3',
    category: 'thinkingofyou',
    name: 'Thinking of You 3',
    title: 'Thinking of You',
    frontImage: require('@/assets/images/cards/thinkingofyou/thinkingofyou-3.png'),
    backMessage: 'Just wanted you to know you are on my mind and in my heart today.',
    color: '#A8B59A',
  },
  {
    id: 'thinkingofyou-4',
    category: 'thinkingofyou',
    name: 'Thinking of You 4',
    title: 'Thinking of You',
    frontImage: require('@/assets/images/cards/thinkingofyou/thinkingofyou-4.png'),
    backMessage: 'Just wanted you to know you are on my mind and in my heart today.',
    color: '#A8B59A',
  },
  {
    id: 'thinkingofyou-5',
    category: 'thinkingofyou',
    name: 'Thinking of You 5',
    title: 'Thinking of You',
    frontImage: require('@/assets/images/cards/thinkingofyou/thinkingofyou-5.png'),
    backMessage: 'Just wanted you to know you are on my mind and in my heart today.',
    color: '#A8B59A',
  },

  // Motivation
  {
    id: 'motivation-1',
    category: 'motivation',
    name: 'Motivation 1',
    title: 'You Got This!',
    frontImage: require('@/assets/images/cards/motivation/motivation-1.png'),
    backMessage: 'Believing in you today and always. Keep going, you are doing amazing.',
    color: '#9CA986',
  },
  {
    id: 'motivation-2',
    category: 'motivation',
    name: 'Motivation 2',
    title: 'You Got This!',
    frontImage: require('@/assets/images/cards/motivation/motivation-2.png'),
    backMessage: 'Believing in you today and always. Keep going, you are doing amazing.',
    color: '#9CA986',
  },
  {
    id: 'motivation-3',
    category: 'motivation',
    name: 'Motivation 3',
    title: 'You Got This!',
    frontImage: require('@/assets/images/cards/motivation/motivation-3.png'),
    backMessage: 'Believing in you today and always. Keep going, you are doing amazing.',
    color: '#9CA986',
  },
  {
    id: 'motivation-4',
    category: 'motivation',
    name: 'Motivation 4',
    title: 'You Got This!',
    frontImage: require('@/assets/images/cards/motivation/motivation-4.png'),
    backMessage: 'Believing in you today and always. Keep going, you are doing amazing.',
    color: '#9CA986',
  },
  {
    id: 'motivation-5',
    category: 'motivation',
    name: 'Motivation 5',
    title: 'You Got This!',
    frontImage: require('@/assets/images/cards/motivation/motivation-5.png'),
    backMessage: 'Believing in you today and always. Keep going, you are doing amazing.',
    color: '#9CA986',
  },

  // Surprise
  {
    id: 'surprise-1',
    category: 'surprise',
    name: 'Surprise 1',
    title: 'Surprise!',
    frontImage: require('@/assets/images/cards/surprise/surprise-1.png'),
    backMessage: 'Something special is coming your way. Hope this brings a smile to your day!',
    color: '#FDE047',
  },
  {
    id: 'surprise-2',
    category: 'surprise',
    name: 'Surprise 2',
    title: 'Surprise!',
    frontImage: require('@/assets/images/cards/surprise/surprise-2.png'),
    backMessage: 'Something special is coming your way. Hope this brings a smile to your day!',
    color: '#FDE047',
  },
  {
    id: 'surprise-3',
    category: 'surprise',
    name: 'Surprise 3',
    title: 'Surprise!',
    frontImage: require('@/assets/images/cards/surprise/surprise-3.png'),
    backMessage: 'Something special is coming your way. Hope this brings a smile to your day!',
    color: '#FDE047',
  },
  {
    id: 'surprise-4',
    category: 'surprise',
    name: 'Surprise 4',
    title: 'Surprise!',
    frontImage: require('@/assets/images/cards/surprise/surprise-4.jpg'),
    backMessage: 'Something special is coming your way. Hope this brings a smile to your day!',
    color: '#FDE047',
  },
  {
    id: 'surprise-5',
    category: 'surprise',
    name: 'Surprise 5',
    title: 'Surprise!',
    frontImage: require('@/assets/images/cards/surprise/surprise-5.jpg'),
    backMessage: 'Something special is coming your way. Hope this brings a smile to your day!',
    color: '#FDE047',
  },
];

export const categoryLabels: Record<CardCategory, string> = {
  birthday: 'Birthday',
  anniversary: 'Anniversary',
  thankyou: 'Thank You',
  valentines: 'Valentine\'s Day',
  wedding: 'Wedding',
  engagement: 'Engagement',
  babyshower: 'Baby Shower',
  graduation: 'Graduation',
  getwellsoon: 'Get Well Soon',
  mothersday: 'Mother\'s Day',
  fathersday: 'Father\'s Day',
  christmas: 'Christmas',
  hanukkah: 'Hanukkah',
  newyear: 'New Year',
  lunarnewyear: 'Lunar New Year',
  easter: 'Easter',
  diwali: 'Diwali',
  ramadan: 'Ramadan',
  vesak: 'Vesak',
  juneteenth: 'Juneteenth',
  invitation: 'Invitation',
  thinkingofyou: 'Thinking of You',
  motivation: 'Motivation',
  surprise: 'Surprise',
};
