export type CardCategory = 'birthday' | 'anniversary' | 'thankyou' | 'love' | 'congratulations' | 'sympathy' | 'justbecause' | 'christmas' | 'hanukkah' | 'mothersday' | 'fathersday' | 'getwellsoon' | 'babyshower' | 'graduation' | 'wedding';

export interface CardTemplate {
  id: string;
  category: CardCategory;
  name: string;
  title: string;
  frontImage: string | number;
  backMessage: string;
  color: string;
}

export const cardTemplates: CardTemplate[] = [
  // Birthday
  {
    id: 'bday-1',
    category: 'birthday',
    name: 'Pastel Balloons',
    title: 'Happy Birthday!',
    frontImage: require('@/assets/images/birthday-pastel-balloons.png'),
    backMessage: 'Wishing you a day filled with love, laughter, and all your heart desires. May this year bring you endless joy!',
    color: '#FFB6C1',
  },
  {
    id: 'bday-2',
    category: 'birthday',
    name: "You're Invited",
    title: "You're Invited!",
    frontImage: require('@/assets/images/birthday-youre-invited.png'),
    backMessage: "You're invited to celebrate! Join us for a special birthday filled with love, laughter, and fun!",
    color: '#E8DCC8',
  },
  {
    id: 'bday-3',
    category: 'birthday',
    name: 'Party Bow Cake',
    title: 'Happy Birthday!',
    frontImage: require('@/assets/images/birthday-party-bow-cake.png'),
    backMessage: "You are invited to the Birthday Party! Let's make this day unforgettable with joy and celebration.",
    color: '#F4A5A5',
  },
  {
    id: 'bday-4',
    category: 'birthday',
    name: 'Colorful Festive',
    title: 'Happy Birthday!',
    frontImage: require('@/assets/images/birthday-colorful-festive.png'),
    backMessage: 'Happy Birthday! May your special day be filled with laughter, love, and unforgettable moments!',
    color: '#A8D5A8',
  },
  {
    id: 'bday-5',
    category: 'birthday',
    name: 'Balloons & Confetti',
    title: 'Happy Birthday!',
    frontImage: require('@/assets/images/birthday-balloons-confetti.png'),
    backMessage: 'Happy Birthday! Wishing you a day as colorful and joyful as you are. Celebrate big!',
    color: '#6B8DC9',
  },
  {
    id: 'bday-6',
    category: 'birthday',
    name: 'Party Celebration',
    title: 'Happy Birthday!',
    frontImage: require('@/assets/images/birthday-party-celebration.png'),
    backMessage: 'Happy Birthday! Let the party begin! Wishing you a day filled with fun, laughter, and wonderful memories!',
    color: '#F5E8D8',
  },
  {
    id: 'bday-7',
    category: 'birthday',
    name: 'Sweet Cakes',
    title: 'Happy Birthday!',
    frontImage: require('@/assets/images/birthday-sweet-cakes.png'),
    backMessage: 'Happy Birthday! May your day be as sweet and colorful as these delicious treats. Celebrate big!',
    color: '#FFF5E6',
  },
  {
    id: 'bday-8',
    category: 'birthday',
    name: 'Record Player',
    title: 'Happy Birthday!',
    frontImage: require('@/assets/images/birthday-record-player.png'),
    backMessage: "For the record, you're not old - you are a classic! Happy Birthday to someone truly timeless!",
    color: '#F8F8F8',
  },
  {
    id: 'bday-9',
    category: 'birthday',
    name: 'Minimalist Candle',
    title: 'Happy Birthday!',
    frontImage: require('@/assets/images/birthday-minimalist-candle.png'),
    backMessage: 'Happy Birthday to You! Wishing you a day filled with love, laughter, and all the joy your heart can hold.',
    color: '#F0E6D8',
  },
  {
    id: 'bday-10',
    category: 'birthday',
    name: 'Snappy Crocodile',
    title: 'Happy Birthday!',
    frontImage: require('@/assets/images/birthday-snappy-crocodile.png'),
    backMessage: 'Have a snappy, happy birthday! Hope your day is filled with fun, laughter, and lots of cake!',
    color: '#4ECDC4',
  },
  {
    id: 'bday-11',
    category: 'birthday',
    name: "Where's the Cake?",
    title: 'Happy Birthday!',
    frontImage: require('@/assets/images/birthday-cat-wheres-the-cake.png'),
    backMessage: "Happy Birthday! Where's the cake? Let's celebrate YOU today with lots of treats and smiles!",
    color: '#F5F5F5',
  },
  {
    id: 'bday-12',
    category: 'birthday',
    name: 'Purrfect Party',
    title: 'Happy Birthday!',
    frontImage: require('@/assets/images/birthday-purrfect-party-cats.png'),
    backMessage: 'Have a purrfect birthday! Hope your day is filled with fun, laughter, and lots of feline good times!',
    color: '#F4C4C4',
  },
  // Anniversary
  {
    id: 'anniv-1',
    category: 'anniversary',
    name: 'Gold Balloons',
    title: 'Happy Anniversary!',
    frontImage: require('@/assets/images/anniversary-gold-balloons.png'),
    backMessage: 'Every moment with you is a treasure. Here is to many more beautiful years together. Happy Anniversary!',
    color: '#FFE4E1',
  },
  {
    id: 'anniv-2',
    category: 'anniversary',
    name: 'Romantic Roses',
    title: 'Happy Anniversary!',
    frontImage: 'https://images.unsplash.com/photo-1518568814500-bf0f8d125f46?w=400&q=80',
    backMessage: 'Every year with you is more beautiful than the last. Happy Anniversary, my love — here is to forever.',
    color: '#E8B4C0',
  },
  {
    id: 'anniv-3',
    category: 'anniversary',
    name: 'Champagne Toast',
    title: 'Happy Anniversary!',
    frontImage: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&q=80',
    backMessage: 'Cheers to another year of love, laughter, and endless adventure. Happy Anniversary!',
    color: '#F5E6C8',
  },
  {
    id: 'anniv-4',
    category: 'anniversary',
    name: 'Eternal Love',
    title: 'Happy Anniversary!',
    frontImage: 'https://images.unsplash.com/photo-1522198684868-88edd8463fc9?w=400&q=80',
    backMessage: 'With you, every day is an anniversary worth celebrating. I love you more than words can say.',
    color: '#F4D6DC',
  },
  {
    id: 'anniv-5',
    category: 'anniversary',
    name: 'Floral Elegance',
    title: 'Happy Anniversary!',
    frontImage: 'https://images.unsplash.com/photo-1490750967868-88df5691cc46?w=400&q=80',
    backMessage: 'Like flowers in bloom, our love grows more beautiful with every passing year. Happy Anniversary!',
    color: '#F0E8F0',
  },
  // Thank You
  {
    id: 'thanks-1',
    category: 'thankyou',
    name: 'Willow Branch',
    title: 'Thank You!',
    frontImage: require('@/assets/images/thankyou-willow-branch.png'),
    backMessage: 'Thank you from the bottom of my heart. Your thoughtfulness touched me deeply.',
    color: '#F5F0ED',
  },
  {
    id: 'thanks-2',
    category: 'thankyou',
    name: 'You Are Awesome',
    title: 'Thank You!',
    frontImage: require('@/assets/images/thankyou-you-are-awesome.png'),
    backMessage: 'You are absolutely awesome! Thank you for being so amazing and making everything brighter.',
    color: '#F4C2D4',
  },
  {
    id: 'thanks-3',
    category: 'thankyou',
    name: 'Classy Green',
    title: 'Thank You!',
    frontImage: require('@/assets/images/thankyou-green-classy.png'),
    backMessage: 'Thank you for your kindness and thoughtfulness. Your support means more than you know.',
    color: '#3E5A4F',
  },
  {
    id: 'thanks-4',
    category: 'thankyou',
    name: 'Bold Modern',
    title: 'Thank You!',
    frontImage: require('@/assets/images/thankyou-bold-modern.png'),
    backMessage: 'Thank You! Thank You! Thank You! Your generosity and support are truly appreciated.',
    color: '#E89BAE',
  },
  {
    id: 'thanks-5',
    category: 'thankyou',
    name: 'Floral Gratitude',
    title: 'Thank You!',
    frontImage: 'https://images.unsplash.com/photo-1607400201515-c2c41c4de9a5?w=400&q=80',
    backMessage: 'A heartfelt thank you for your incredible kindness. You made such a meaningful difference.',
    color: '#E8F0E8',
  },
  // Love & Valentine's Day
  {
    id: 'love-1',
    category: 'love',
    name: 'Hanging Hearts',
    title: 'Happy Valentine\'s Day!',
    frontImage: require('@/assets/images/valentines-hanging-hearts.png'),
    backMessage: "Happy Valentine's Day! My love for you hangs on every heartbeat. You mean the world to me.",
    color: '#F5F5F5',
  },
  {
    id: 'love-2',
    category: 'love',
    name: 'Heart Minimal',
    title: 'With Love',
    frontImage: require('@/assets/images/valentines-heart-minimal.png'),
    backMessage: 'You are my favorite person, my greatest adventure, and my forever love.',
    color: '#FF69B4',
  },
  {
    id: 'love-3',
    category: 'love',
    name: "I'm Yours (No Returns)",
    title: "I'm Yours!",
    frontImage: require('@/assets/images/valentines-im-yours-no-returns.png'),
    backMessage: "I am yours - completely and forever! Happy Valentine's Day to the one who owns my heart.",
    color: '#FCEDEF',
  },
  {
    id: 'love-4',
    category: 'love',
    name: 'King of Hearts',
    title: 'Happy Valentine\'s Day!',
    frontImage: require('@/assets/images/valentines-king-hearts.png'),
    backMessage: "For the love of my life - Happy Valentine's Day!",
    color: '#FFB4C8',
  },
  {
    id: 'love-5',
    category: 'love',
    name: 'Paper Hearts',
    title: 'Happy Valentine\'s Day!',
    frontImage: require('@/assets/images/valentines-paper-hearts.png'),
    backMessage: "Happy Valentine's Day! You make my heart skip a beat. Here's to our love story that keeps getting better.",
    color: '#F4D6DC',
  },
  {
    id: 'love-6',
    category: 'love',
    name: 'Playing Cards',
    title: 'With Love',
    frontImage: require('@/assets/images/valentines-playing-cards.png'),
    backMessage: "I'm so lucky to have you. Every day with you is a winning hand!",
    color: '#F47983',
  },
  {
    id: 'love-7',
    category: 'love',
    name: 'Watercolor Hearts',
    title: 'Happy Valentine\'s Day!',
    frontImage: require('@/assets/images/valentines-watercolor-hearts.png'),
    backMessage: "Happy Valentine's Day! Every moment with you is painted with love. You are my everything.",
    color: '#F9E4E8',
  },
  {
    id: 'love-8',
    category: 'love',
    name: "You're My Jam",
    title: 'With Love',
    frontImage: require('@/assets/images/valentines-youre-my-jam.png'),
    backMessage: "You're my jam! Happy Valentine's Day to the sweetest person I know. Love you berry much!",
    color: '#FCF0F0',
  },
  {
    id: 'love-9',
    category: 'love',
    name: 'Thinking of You',
    title: 'Thinking of You',
    frontImage: require('@/assets/images/thinking-of-you-hearts.png'),
    backMessage: 'I never stop thinking about you. Every moment with you feels like a story I never want to end.',
    color: '#F4E4D7',
  },
  // Sympathy
  {
    id: 'sympathy-1',
    category: 'sympathy',
    name: 'Peaceful White Flowers',
    title: 'With Deepest Sympathy',
    frontImage: 'https://images.unsplash.com/photo-1524593689594-aae2f26b75ab?w=400&q=80',
    backMessage: 'Sending you love and light during this difficult time. May you find comfort and peace in the days ahead.',
    color: '#F8F8F8',
  },
  {
    id: 'sympathy-2',
    category: 'sympathy',
    name: 'Gentle Candle',
    title: 'With Deepest Sympathy',
    frontImage: 'https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=400&q=80',
    backMessage: 'May the memories you cherish bring you comfort and the love around you bring you strength.',
    color: '#F5F0E8',
  },
  {
    id: 'sympathy-3',
    category: 'sympathy',
    name: 'Soft Petals',
    title: 'With Deepest Sympathy',
    frontImage: 'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=400&q=80',
    backMessage: 'With deepest sympathy. You are in our thoughts and hearts during this time of sorrow.',
    color: '#F0E8EC',
  },
  {
    id: 'sympathy-4',
    category: 'sympathy',
    name: 'Serene Garden',
    title: 'In Loving Memory',
    frontImage: 'https://images.unsplash.com/photo-1455218873509-8097305ee378?w=400&q=80',
    backMessage: 'There are no words adequate enough, but please know we are here for you with all our love.',
    color: '#E8F0E8',
  },
  {
    id: 'sympathy-5',
    category: 'sympathy',
    name: 'Warm Light',
    title: 'Thinking of You',
    frontImage: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=400&q=80',
    backMessage: 'Holding you close in our thoughts and wishing you moments of peace and healing.',
    color: '#F5EDE8',
  },
  // Congratulations
  {
    id: 'congrats-1',
    category: 'congratulations',
    name: 'Confetti Pattern',
    title: 'Congratulations!',
    frontImage: require('@/assets/images/congrats-confetti-pattern.png'),
    backMessage: 'Congratulations! You did it! Celebrating this amazing achievement with you. Well deserved success!',
    color: '#F5F5F5',
  },
  {
    id: 'congrats-2',
    category: 'congratulations',
    name: 'Watercolor Brushstroke',
    title: 'Congratulations!',
    frontImage: require('@/assets/images/congrats-watercolor-brushstroke.png'),
    backMessage: 'Your hard work and dedication have paid off! So proud of everything you have accomplished.',
    color: '#F0DDE4',
  },
  {
    id: 'congrats-3',
    category: 'congratulations',
    name: 'New Baby Watercolor',
    title: 'Congratulations!',
    frontImage: require('@/assets/images/congrats-baby-watercolor.png'),
    backMessage: 'Congratulations on the birth of your beautiful baby! Wishing your family endless love, joy, and precious moments.',
    color: '#D4E8E4',
  },
  {
    id: 'congrats-4',
    category: 'congratulations',
    name: 'Cheers to Forever',
    title: 'Congratulations!',
    frontImage: require('@/assets/images/engagement-cheers.png'),
    backMessage: 'Congratulations on your engagement! Cheers to forever together! Wishing you a lifetime of love and happiness.',
    color: '#F5F0ED',
  },
  {
    id: 'congrats-5',
    category: 'congratulations',
    name: 'Engagement Floral',
    title: 'Congratulations!',
    frontImage: require('@/assets/images/engagement-congratulations-floral.png'),
    backMessage: 'Congratulations on your engagement! Wishing you both a lifetime of love, happiness, and beautiful moments together.',
    color: '#F5F0E8',
  },
  // Just Because
  {
    id: 'just-1',
    category: 'justbecause',
    name: 'Dinner Party',
    title: 'You Are Invited!',
    frontImage: require('@/assets/images/dinner-party-invitation.png'),
    backMessage: 'Join us for a Dinner Party! Good food, great company, and wonderful memories await.',
    color: '#F5E6D3',
  },
  {
    id: 'just-2',
    category: 'justbecause',
    name: 'Thinking of You',
    title: 'Thinking of You',
    frontImage: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=400&q=80',
    backMessage: 'Just wanted to reach out and let you know I am thinking of you today. Hope you are doing wonderfully!',
    color: '#FDE8EF',
  },
  {
    id: 'just-3',
    category: 'justbecause',
    name: 'You Are Wonderful',
    title: 'Just Because',
    frontImage: 'https://images.unsplash.com/photo-1504439468489-c8920d796a29?w=400&q=80',
    backMessage: 'No special reason — just wanted to remind you how amazing and wonderful you truly are.',
    color: '#E8F4FD',
  },
  {
    id: 'just-4',
    category: 'justbecause',
    name: 'Bright Day',
    title: 'Just Because',
    frontImage: 'https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?w=400&q=80',
    backMessage: 'Sending you a little sunshine to brighten your day — just because you deserve it!',
    color: '#FFF9E6',
  },
  {
    id: 'just-5',
    category: 'justbecause',
    name: 'Missing You',
    title: 'Missing You',
    frontImage: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=400&q=80',
    backMessage: 'I have been thinking about you and just wanted to say — I miss you and I hope to see you soon!',
    color: '#F0E8F8',
  },
  // Christmas
  {
    id: 'christmas-1',
    category: 'christmas',
    name: 'Vintage Basket',
    title: 'Merry Christmas!',
    frontImage: require('@/assets/images/christmas-vintage-basket.png'),
    backMessage: 'Wishing you a warm and wonderful Christmas filled with joy, love, and cherished moments.',
    color: '#E8DCC8',
  },
  {
    id: 'christmas-2',
    category: 'christmas',
    name: 'Green Ornaments',
    title: 'Merry Christmas!',
    frontImage: require('@/assets/images/christmas-ornaments-green.png'),
    backMessage: 'Merry Christmas and Happy New Year! May your holidays be filled with warmth, joy, and beautiful memories.',
    color: '#5D8C6F',
  },
  {
    id: 'christmas-3',
    category: 'christmas',
    name: 'Green Festivities',
    title: 'Merry Christmas!',
    frontImage: require('@/assets/images/christmas-green-festivities.png'),
    backMessage: 'Be a part of our Merry Christmas Festivities! Wishing you joy, warmth, and wonderful memories this holiday season.',
    color: '#2C5F4D',
  },
  {
    id: 'christmas-4',
    category: 'christmas',
    name: 'All I Want is Booze',
    title: 'Happy Holidays!',
    frontImage: require('@/assets/images/christmas-all-i-want-is-booze.png'),
    backMessage: 'Cheers to the holiday season! Raising a glass to friendship, love, and all the magic of Christmas.',
    color: '#E8DCC8',
  },
  {
    id: 'christmas-5',
    category: 'christmas',
    name: 'Favorite Snowman',
    title: 'Merry Christmas!',
    frontImage: require('@/assets/images/christmas-favorite-flake-snowman.png'),
    backMessage: 'Merry Christmas! Wishing you a season filled with joy, warmth, and lots of festive fun!',
    color: '#B8E6F0',
  },
  // Hanukkah
  {
    id: 'hanukkah-1',
    category: 'hanukkah',
    name: 'Blue & White',
    title: 'Happy Hanukkah!',
    frontImage: require('@/assets/images/hanukkah-blue-white.png'),
    backMessage: 'May this season be filled with peace, love, and happiness. Happy Hanukkah!',
    color: '#A8C8E1',
  },
  {
    id: 'hanukkah-2',
    category: 'hanukkah',
    name: 'Yellow Window',
    title: 'Happy Hanukkah!',
    frontImage: require('@/assets/images/hanukkah-yellow-window.png'),
    backMessage: 'Wishing you and your family peace and light this holiday season. Happy Hanukkah from our family to yours!',
    color: '#F4D35E',
  },
  {
    id: 'hanukkah-3',
    category: 'hanukkah',
    name: 'Festival of Lights',
    title: 'Happy Hanukkah!',
    frontImage: 'https://images.unsplash.com/photo-1607131154835-b3d0c43a46f1?w=400&q=80',
    backMessage: 'May the Festival of Lights fill your home with warmth, joy, and the miracle of Hanukkah.',
    color: '#D4E8F0',
  },
  {
    id: 'hanukkah-4',
    category: 'hanukkah',
    name: 'Eight Nights',
    title: 'Happy Hanukkah!',
    frontImage: 'https://images.unsplash.com/photo-1575389972987-f6cf5e3a6bb6?w=400&q=80',
    backMessage: 'Eight nights of light, love, and miracles. Wishing you and yours a joyful and blessed Hanukkah.',
    color: '#E8F0F8',
  },
  {
    id: 'hanukkah-5',
    category: 'hanukkah',
    name: 'Dreidel Magic',
    title: 'Happy Hanukkah!',
    frontImage: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&q=80',
    backMessage: 'May your Hanukkah be filled with the joy of the season and the warmth of family and friends.',
    color: '#F8F4E8',
  },
  // Mother's Day
  {
    id: 'mothersday-1',
    category: 'mothersday',
    name: 'Flower Heart',
    title: "Happy Mother's Day!",
    frontImage: require('@/assets/images/mothers-day-flower-heart.png'),
    backMessage: "Happy Mother's Day with love! Thank you for your endless love, support, and everything you do. You are truly cherished.",
    color: '#F5C6D5',
  },
  {
    id: 'mothersday-2',
    category: 'mothersday',
    name: 'Red Bouquet',
    title: "Happy Mother's Day!",
    frontImage: require('@/assets/images/mothers-day-bouquet-red.png'),
    backMessage: "Happy Mother's Day! Celebrating the amazing, caring, and wonderful person you are. Love you always!",
    color: '#E74C5E',
  },
  {
    id: 'mothersday-3',
    category: 'mothersday',
    name: 'Watercolor Bouquet',
    title: "Happy Mother's Day!",
    frontImage: require('@/assets/images/mothers-day-bouquet-watercolor.png'),
    backMessage: "Happy Mother's Day! Your love and warmth make every day brighter. Thank you for being extraordinary.",
    color: '#F9E4E8',
  },
  {
    id: 'mothersday-4',
    category: 'mothersday',
    name: 'Garden of Love',
    title: "Happy Mother's Day!",
    frontImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    backMessage: "Happy Mother's Day! Like a garden, your love nurtures everything it touches. Thank you for being you.",
    color: '#F0F4E8',
  },
  {
    id: 'mothersday-5',
    category: 'mothersday',
    name: 'Sweet Morning',
    title: "Happy Mother's Day!",
    frontImage: 'https://images.unsplash.com/photo-1489710437720-ebb67ec84dd2?w=400&q=80',
    backMessage: "Wishing you a beautiful Mother's Day filled with rest, joy, and all the love you give so freely.",
    color: '#FEF0E8',
  },
  // Father's Day
  {
    id: 'fathersday-1',
    category: 'fathersday',
    name: 'Classic Tie',
    title: "Happy Father's Day!",
    frontImage: require('@/assets/images/fathers-day-tie.png'),
    backMessage: "Happy Father's Day! You are my hero without a cape and my calm harbor. Thank you for everything you do.",
    color: '#1F2937',
  },
  {
    id: 'fathersday-2',
    category: 'fathersday',
    name: 'Adventure Dad',
    title: "Happy Father's Day!",
    frontImage: 'https://images.unsplash.com/photo-1475503572774-15a45e5d60b9?w=400&q=80',
    backMessage: "Happy Father's Day! Thanks for every adventure, every lesson, and every moment of being the best dad.",
    color: '#E8F0F8',
  },
  {
    id: 'fathersday-3',
    category: 'fathersday',
    name: 'Great Outdoors',
    title: "Happy Father's Day!",
    frontImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&q=80',
    backMessage: "To the man who showed me the world — Happy Father's Day! You are my greatest adventure.",
    color: '#E8F4EC',
  },
  {
    id: 'fathersday-4',
    category: 'fathersday',
    name: 'Super Dad',
    title: "Happy Father's Day!",
    frontImage: 'https://images.unsplash.com/photo-1488998527040-85054a85150e?w=400&q=80',
    backMessage: "You are not just my dad — you are my superhero. Happy Father's Day with all my love!",
    color: '#EDE8F8',
  },
  {
    id: 'fathersday-5',
    category: 'fathersday',
    name: 'Coffee & Love',
    title: "Happy Father's Day!",
    frontImage: 'https://images.unsplash.com/photo-1497515114629-f71d768fd07c?w=400&q=80',
    backMessage: "Happy Father's Day! Thanks for every cup of coffee, every piece of advice, and every moment of your time.",
    color: '#F5EDE0',
  },
  // Get Well Soon
  {
    id: 'getwellsoon-1',
    category: 'getwellsoon',
    name: 'Get Well Cat',
    title: 'Get Well Soon!',
    frontImage: require('@/assets/images/get-well-soon-cat.png'),
    backMessage: 'Get Well Soon! Sending you lots of love and healing thoughts. Hope you feel better very soon!',
    color: '#F4D4DD',
  },
  {
    id: 'getwellsoon-2',
    category: 'getwellsoon',
    name: 'Feel Better Flowers',
    title: 'Get Well Soon!',
    frontImage: require('@/assets/images/get-well-soon-flowers.png'),
    backMessage: 'Feel better soon! Sending you a bouquet of healing wishes and positive thoughts for a speedy recovery.',
    color: '#D4E8E8',
  },
  {
    id: 'getwellsoon-3',
    category: 'getwellsoon',
    name: 'Warm Tea',
    title: 'Get Well Soon!',
    frontImage: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400&q=80',
    backMessage: 'Sending you warmth and comfort. Take it easy, rest up, and know we are all rooting for you!',
    color: '#F5EDE0',
  },
  {
    id: 'getwellsoon-4',
    category: 'getwellsoon',
    name: 'Sunny Garden',
    title: 'Wishing You Well',
    frontImage: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&q=80',
    backMessage: 'Wishing you sunshine and healing. Each day is a step closer to feeling wonderful again!',
    color: '#FFF8E8',
  },
  {
    id: 'getwellsoon-5',
    category: 'getwellsoon',
    name: 'Healing Hands',
    title: 'Feel Better Soon!',
    frontImage: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=400&q=80',
    backMessage: 'You are stronger than you know. Sending healing thoughts and warm wishes your way.',
    color: '#EAF4F0',
  },
  // Baby Shower
  {
    id: 'babyshower-1',
    category: 'babyshower',
    name: "It's a Girl",
    title: "It's a Girl!",
    frontImage: require('@/assets/images/baby-shower-its-a-girl.png'),
    backMessage: "It's a Girl! Congratulations on your bundle of joy! Wishing you all the love and happiness as you welcome your little one.",
    color: '#F4DAE4',
  },
  {
    id: 'babyshower-2',
    category: 'babyshower',
    name: "It's a Boy",
    title: "It's a Boy!",
    frontImage: 'https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=400&q=80',
    backMessage: "It's a Boy! Congratulations! Wishing your family all the joy, love, and tiny blue adventures ahead.",
    color: '#C8E0F4',
  },
  {
    id: 'babyshower-3',
    category: 'babyshower',
    name: 'Baby Sprinkle',
    title: 'Baby Shower!',
    frontImage: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=400&q=80',
    backMessage: 'A new little life is on the way! Showering you with love, blessings, and all good things.',
    color: '#F4E8F8',
  },
  {
    id: 'babyshower-4',
    category: 'babyshower',
    name: 'Tiny Toes',
    title: 'Welcome Baby!',
    frontImage: 'https://images.unsplash.com/photo-1478369402113-1fd53f17e8b4?w=400&q=80',
    backMessage: 'The tiniest feet make the biggest footprint on our hearts. Congratulations on your growing family!',
    color: '#F8F0E8',
  },
  {
    id: 'babyshower-5',
    category: 'babyshower',
    name: 'Welcome Little One',
    title: 'Welcome Little One!',
    frontImage: 'https://images.unsplash.com/photo-1588776814546-1ffbb71de06a?w=400&q=80',
    backMessage: 'Welcome to the world, little one! You are already so loved beyond measure.',
    color: '#EAF4EC',
  },
  // Graduation
  {
    id: 'graduation-1',
    category: 'graduation',
    name: 'Cap & Flowers',
    title: 'Congratulations, Graduate!',
    frontImage: require('@/assets/images/graduation-cap-flowers.png'),
    backMessage: 'Happy Graduation! Congratulations on this incredible achievement! Your hard work and dedication have paid off. The future is bright!',
    color: '#E8DCC8',
  },
  {
    id: 'graduation-2',
    category: 'graduation',
    name: 'Graduation Celebration',
    title: 'Happy Graduation!',
    frontImage: require('@/assets/images/graduation-celebration.png'),
    backMessage: 'Happy Graduation! You did it! The future is yours. Wishing you all the success and happiness in your next adventure!',
    color: '#F0E6D3',
  },
  {
    id: 'graduation-3',
    category: 'graduation',
    name: 'Next Chapter',
    title: 'Happy Graduation!',
    frontImage: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=400&q=80',
    backMessage: 'The tassel was worth the hassle! Congratulations, graduate — your next great chapter begins now.',
    color: '#E8EAF4',
  },
  {
    id: 'graduation-4',
    category: 'graduation',
    name: 'Class of the Year',
    title: 'Congratulations, Graduate!',
    frontImage: 'https://images.unsplash.com/photo-1627556704302-624286467c65?w=400&q=80',
    backMessage: 'Congratulations, graduate! Your hard work and perseverance have led you to this incredible milestone.',
    color: '#F4EAD4',
  },
  {
    id: 'graduation-5',
    category: 'graduation',
    name: 'Future is Yours',
    title: 'Happy Graduation!',
    frontImage: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=400&q=80',
    backMessage: 'You did it! The world is waiting and the future is brilliantly yours. Congratulations!',
    color: '#EAF4F0',
  },
  // Wedding
  {
    id: 'wedding-1',
    category: 'wedding',
    name: 'Golden Rings',
    title: 'Congratulations!',
    frontImage: require('@/assets/images/wedding-golden-rings.png'),
    backMessage: 'Happy Wedding! Congratulations on your special day. Wishing you a lifetime of love, joy, and beautiful moments together.',
    color: '#F4EDD8',
  },
  {
    id: 'wedding-2',
    category: 'wedding',
    name: 'Save the Date Floral',
    title: 'Save the Date!',
    frontImage: require('@/assets/images/wedding-save-the-date-floral.png'),
    backMessage: 'Save the Date! We would be honored to have you celebrate our special day with us. More details to follow!',
    color: '#F4D8E0',
  },
  {
    id: 'wedding-3',
    category: 'wedding',
    name: 'Garden Wedding',
    title: 'Congratulations!',
    frontImage: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=400&q=80',
    backMessage: 'Two hearts, one love, one perfect day. Congratulations on your beautiful wedding!',
    color: '#E8F4E8',
  },
  {
    id: 'wedding-4',
    category: 'wedding',
    name: 'White Romance',
    title: 'Congratulations!',
    frontImage: 'https://images.unsplash.com/photo-1537633552985-df8429e8048b?w=400&q=80',
    backMessage: 'Wishing you a love that grows deeper and a bond that grows stronger with every passing year. Congratulations!',
    color: '#F8F4F0',
  },
  {
    id: 'wedding-5',
    category: 'wedding',
    name: 'Floral Arch',
    title: 'Congratulations!',
    frontImage: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=400&q=80',
    backMessage: 'May your marriage be filled with laughter, adventure, and a lifetime of happiness together.',
    color: '#F4EDF8',
  },
];

export const categoryLabels: Record<CardCategory, string> = {
  birthday: 'Birthday',
  anniversary: 'Anniversary',
  thankyou: 'Thank You',
  love: 'Love',
  congratulations: 'Congratulations',
  sympathy: 'Sympathy',
  justbecause: 'Just Because',
  christmas: 'Christmas',
  hanukkah: 'Hanukkah',
  mothersday: "Mother's Day",
  fathersday: "Father's Day",
  getwellsoon: 'Get Well Soon',
  babyshower: 'Baby Shower',
  graduation: 'Graduation',
  wedding: 'Wedding',
};
