export const theme = {
  colors: {
    primary: '#C17B66',
    primaryLight: '#E8C4B8',
    primaryDark: '#9E5E4E',
    cream: '#FAF7F4',
    creamDark: '#F0EBE5',
    white: '#FFFFFF',
    dark: '#1A1A1A',
    charcoal: '#2C2C2C',
    lightGray: '#EBEBEB',
    borderGray: '#E0DADA',
    mediumGray: '#9E9E9E',
    success: '#5C9E6B',
    error: '#C05050',
    errorLight: '#FEF0F0',
    overlay: 'rgba(26,26,26,0.55)',
  },
  fonts: {
    script: 'cursive',
    serif: 'serif',
    sans: 'System',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    xs: 6,
    sm: 10,
    md: 14,
    lg: 20,
    xl: 28,
    full: 999,
  },
  shadows: {
    soft: {
      shadowColor: '#C17B66',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 10,
      elevation: 2,
    },
    card: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.07,
      shadowRadius: 12,
      elevation: 3,
    },
    elevated: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.12,
      shadowRadius: 18,
      elevation: 8,
    },
    fab: {
      shadowColor: '#C17B66',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.35,
      shadowRadius: 12,
      elevation: 8,
    },
  },
};
